version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build:
      context: ./client
      dockerfile: ../docker/frontend.Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
    command: npm start

volumes:
  go-mod-cache:
