version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dev.Dockerfile
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    command: air -c .air.toml

  frontend:
    build:
      context: ./client
      dockerfile: ../docker/frontend.dev.Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  go-mod-cache:
